#!/bin/bash

S3TARGET=$1
shift
for var in "$@"
do
  GZFILE=$var.gz
  pg_dump -Fc --no-acl --no-owner $var | gzip > $TEMP_BACKUP_DIR/$GZFILE
  aws s3 mv $TEMP_BACKUP_DIR/$GZFILE "$S3TARGET/$GZFILE"
done
