#!/bin/bash

S3TARGET=$1
shift
for var in "$@"
do
  OUTFILE=$var.pgdump
  pg_dump -Fc -f $TEMP_BACKUP_DIR/$OUTFILE --no-acl --no-owner $var
  aws s3 mv $TEMP_BACKUP_DIR/$OUTFILE "$S3TARGET/$OUTFILE"
done
